# Version does not matter, it will be overwritten anyway with the tag name
version: 0.{build}
skip_non_tags: true
clone_depth: 15

environment:
  nodejs_version: 8.14.0
  GOPATH: C:\gopath
  GOROOT: C:\go
  GH_TOKEN:
    secure: zkRfj38vtjpl4e3+3l9Lovna+1cQ4/SFBNY6xwhf35j3RDCaTVHmu8M9brnYDRZ8

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%
  - ps: Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
  - set PATH=C:\msys64\mingw64\bin;%PATH%;C:\msys64\usr\bin
  - set CGO_LDFLAGS=-g -O2 -static -static-libgcc -static-libstdc++

install:
  - ps: Install-Product node $env:nodejs_version x64
  - g++ --version
  - git reset --hard HEAD
  - npm install npm -g
  - go version
  - go env
  # Pull all repositories
  - python before_install.py
  - go get -u github.com/golang/dep/cmd/dep
  # Build exccd, exccctl and exccwallet
  - cd %GOPATH%\\src\\github.com\\EXCCoin\\exccd
  - dep ensure
  - go install . ./cmd/exccctl/
  - cd ../exccwallet
  - dep ensure
  - go install
  - cd ../exilibrium
  # Copy binaries to exilibrium
  - if not exist bin mkdir bin
  - cp %GOPATH%\\bin\\exccd.exe bin/exccd64.exe
  - cp %GOPATH%\\bin\\exccctl.exe bin/exccctl64.exe
  - cp %GOPATH%\\bin\\exccwallet.exe bin/exccwallet64.exe
  # Create excc-binaries archive
  - if not exist %APPVEYOR_BUILD_FOLDER%\\artifacts mkdir %APPVEYOR_BUILD_FOLDER%\\artifacts
  - 7z a %APPVEYOR_BUILD_FOLDER%\artifacts\excc-binaries_win64_%date:~10,4%%date:~4,2%%date:~7,2%.zip bin/*
  # Build exilibrium
  - yarn
  - yarn package
  - dir %GOPATH%\\src\\github.com\\EXCCoin\\exilibrium\\release\\
  - copy %GOPATH%\src\github.com\EXCCoin\exilibrium\\release\*.exe %APPVEYOR_BUILD_FOLDER%\artifacts

build_script:
  - echo "Hooray!"

test: off

artifacts:
  - path: '.\artifacts\*.zip'
    type: File
    name: EXCCBinaries
  - path: '.\artifacts\*.exe'
    type: File
    name: ExilibriumRelease

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token: "%GH_TOKEN%"
  artifact: EXCCBinaries,ExilibriumRelease
  draft: false
  prerelease: false
  on:
    # Build tags only
    APPVEYOR_REPO_TAG: true
